import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/layout/Header';
import Sidebar from '@/components/layout/Sidebar';
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const headersList = headers();
  const useLayout = headersList.get('x-use-layout') === 'true';

  if (!useLayout) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body>
        <div>
          <Header />
          <Sidebar />
          <main className="pt-16 pl-64">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
