import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/layout/Header';
import Sidebar from '@/components/layout/Sidebar';
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  content,
}: {
  children: React.ReactNode;
  content: React.ReactNode;
}) {
  const headersList = headers();
  const useLayout = headersList.get('x-use-layout') === 'true';

  if (!useLayout) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <Header />
          <div className="flex flex-1">
            <Sidebar />
            {/* <main className="flex-1 ml-64 mt-16 p-6">
              {children}
            </main> */}
          </div>
          {content}
        </div>
      </body>
    </html>
  );
}
