import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/layout/Header';
import Sidebar from '@/components/layout/Sidebar';
import { headers } from 'next/headers';
import { montserrat } from './fonts';
import AuthProvider from '@/components/providers/SessionProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
